// 标准MBTI题库 - 93题完整版
const fullQuestions = [
  // E/I维度题目 (外向/内向)
  { id: 1, content: "我喜欢成为关注的焦点", dimension: "EI", direction: -1 },
  { id: 2, content: "我喜欢独自一人安静地思考", dimension: "EI", direction: 1 },
  { id: 3, content: "我更喜欢与人交流而不是独处", dimension: "EI", direction: -1 },
  { id: 4, content: "在社交场合，我通常会等待他人来找我交谈", dimension: "EI", direction: 1 },
  { id: 5, content: "我在社交场合容易感到疲惫", dimension: "EI", direction: 1 },
  { id: 6, content: "我倾向于先说出想法，然后再思考", dimension: "EI", direction: -1 },
  { id: 7, content: "我喜欢在大型聚会中认识新朋友", dimension: "EI", direction: -1 },
  { id: 8, content: "我需要独处的时间来恢复精力", dimension: "EI", direction: 1 },
  { id: 9, content: "我通常是小组中的发言者", dimension: "EI", direction: -1 },
  { id: 10, content: "我更喜欢一对一的深入交流", dimension: "EI", direction: 1 },
  { id: 11, content: "我喜欢参加各种社交活动", dimension: "EI", direction: -1 },
  { id: 12, content: "我在做决定前需要时间思考", dimension: "EI", direction: 1 },
  { id: 13, content: "我更喜欢在团队中工作", dimension: "EI", direction: -1 },
  { id: 14, content: "我喜欢有自己的私人空间", dimension: "EI", direction: 1 },
  { id: 15, content: "我经常主动开始对话", dimension: "EI", direction: -1 },
  { id: 16, content: "我喜欢深入研究少数几个话题", dimension: "EI", direction: 1 },
  { id: 17, content: "我的朋友圈通常很广泛", dimension: "EI", direction: -1 },
  { id: 18, content: "我更喜欢安静的环境", dimension: "EI", direction: 1 },
  { id: 19, content: "我喜欢边说边思考", dimension: "EI", direction: -1 },
  { id: 20, content: "我喜欢先思考再行动", dimension: "EI", direction: 1 },
  { id: 21, content: "我容易与陌生人交谈", dimension: "EI", direction: -1 },
  { id: 22, content: "我喜欢独自探索新想法", dimension: "EI", direction: 1 },
  { id: 23, content: "我在团体中通常很活跃", dimension: "EI", direction: -1 },
  
  // S/N维度题目 (感觉/直觉)
  { id: 24, content: "我更关注具体的事实和细节", dimension: "SN", direction: -1 },
  { id: 25, content: "我喜欢思考抽象的概念和可能性", dimension: "SN", direction: 1 },
  { id: 26, content: "我更相信经验和实践", dimension: "SN", direction: -1 },
  { id: 27, content: "我喜欢想象未来的可能性", dimension: "SN", direction: 1 },
  { id: 28, content: "我更关注当下而非未来", dimension: "SN", direction: -1 },
  { id: 29, content: "我经常思考事物的深层含义", dimension: "SN", direction: 1 },
  { id: 30, content: "我喜欢按部就班地解决问题", dimension: "SN", direction: -1 },
  { id: 31, content: "我喜欢探索新的、未经尝试的方法", dimension: "SN", direction: 1 },
  { id: 32, content: "我更相信自己的直接观察", dimension: "SN", direction: -1 },
  { id: 33, content: "我喜欢寻找模式和联系", dimension: "SN", direction: 1 },
  { id: 34, content: "我更喜欢实际的、具体的工作", dimension: "SN", direction: -1 },
  { id: 35, content: "我喜欢思考理论和抽象概念", dimension: "SN", direction: 1 },
  { id: 36, content: "我更关注现实情况而非可能性", dimension: "SN", direction: -1 },
  { id: 37, content: "我喜欢思考事物的潜在发展", dimension: "SN", direction: 1 },
  { id: 38, content: "我更喜欢具体的指导而非概括的描述", dimension: "SN", direction: -1 },
  { id: 39, content: "我经常有创新的想法", dimension: "SN", direction: 1 },
  { id: 40, content: "我更关注细节而非整体", dimension: "SN", direction: -1 },
  { id: 41, content: "我更喜欢关注整体而非细节", dimension: "SN", direction: 1 },
  { id: 42, content: "我喜欢按照既定方法做事", dimension: "SN", direction: -1 },
  { id: 43, content: "我喜欢尝试新方法", dimension: "SN", direction: 1 },
  { id: 44, content: "我更相信自己的实际经验", dimension: "SN", direction: -1 },
  { id: 45, content: "我喜欢思考事物的可能性", dimension: "SN", direction: 1 },
  { id: 46, content: "我更关注'是什么'而非'可能是什么'", dimension: "SN", direction: -1 },
  
  // T/F维度题目 (思考/情感)
  { id: 47, content: "我做决定时更依赖逻辑分析", dimension: "TF", direction: -1 },
  { id: 48, content: "我做决定时更考虑人的感受", dimension: "TF", direction: 1 },
  { id: 49, content: "我认为真相比和谐更重要", dimension: "TF", direction: -1 },
  { id: 50, content: "我容易被他人的情绪影响", dimension: "TF", direction: 1 },
  { id: 51, content: "我更看重公平和一致性", dimension: "TF", direction: -1 },
  { id: 52, content: "我更看重同理心和和谐", dimension: "TF", direction: 1 },
  { id: 53, content: "我倾向于直接指出问题所在", dimension: "TF", direction: -1 },
  { id: 54, content: "我倾向于避免可能导致冲突的话题", dimension: "TF", direction: 1 },
  { id: 55, content: "我更看重客观事实而非个人感受", dimension: "TF", direction: -1 },
  { id: 56, content: "我在做决定时会考虑他人的感受", dimension: "TF", direction: 1 },
  { id: 57, content: "我喜欢分析事物的利弊", dimension: "TF", direction: -1 },
  { id: 58, content: "我喜欢考虑决定对人的影响", dimension: "TF", direction: 1 },
  { id: 59, content: "我更看重效率而非人际和谐", dimension: "TF", direction: -1 },
  { id: 60, content: "我更看重团队和谐而非效率", dimension: "TF", direction: 1 },
  { id: 61, content: "我更看重公正而非仁慈", dimension: "TF", direction: -1 },
  { id: 62, content: "我更看重仁慈而非公正", dimension: "TF", direction: 1 },
  { id: 63, content: "我更相信逻辑而非感觉", dimension: "TF", direction: -1 },
  { id: 64, content: "我更相信感觉而非逻辑", dimension: "TF", direction: 1 },
  { id: 65, content: "我更看重诚实而非善意", dimension: "TF", direction: -1 },
  { id: 66, content: "我更看重善意而非诚实", dimension: "TF", direction: 1 },
  { id: 67, content: "我在批评时直接而坦率", dimension: "TF", direction: -1 },
  { id: 68, content: "我在批评时委婉而体贴", dimension: "TF", direction: 1 },
  { id: 69, content: "我更看重能力而非努力", dimension: "TF", direction: -1 },
  
  // J/P维度题目 (判断/知觉)
  { id: 70, content: "我喜欢提前计划和安排", dimension: "JP", direction: -1 },
  { id: 71, content: "我喜欢保持灵活，随机应变", dimension: "JP", direction: 1 },
  { id: 72, content: "我喜欢有条理的环境", dimension: "JP", direction: -1 },
  { id: 73, content: "我喜欢探索多种可能性", dimension: "JP", direction: 1 },
  { id: 74, content: "我喜欢按计划行事", dimension: "JP", direction: -1 },
  { id: 75, content: "我喜欢即兴决定", dimension: "JP", direction: 1 },
  { id: 76, content: "我喜欢有明确的截止日期", dimension: "JP", direction: -1 },
  { id: 77, content: "我喜欢保持选择的开放性", dimension: "JP", direction: 1 },
  { id: 78, content: "我喜欢提前做决定", dimension: "JP", direction: -1 },
  { id: 79, content: "我喜欢在最后一刻做决定", dimension: "JP", direction: 1 },
  { id: 80, content: "我喜欢按部就班地完成任务", dimension: "JP", direction: -1 },
  { id: 81, content: "我喜欢同时处理多个任务", dimension: "JP", direction: 1 },
  { id: 82, content: "我喜欢有明确的规则和指导", dimension: "JP", direction: -1 },
  { id: 83, content: "我喜欢有灵活性和自由度", dimension: "JP", direction: 1 },
  { id: 84, content: "我喜欢按照清单检查完成情况", dimension: "JP", direction: -1 },
  { id: 85, content: "我喜欢根据情况调整计划", dimension: "JP", direction: 1 },
  { id: 86, content: "我喜欢有序和可预测", dimension: "JP", direction: -1 },
  { id: 87, content: "我喜欢变化和新鲜感", dimension: "JP", direction: 1 },
  { id: 88, content: "我喜欢按时完成任务", dimension: "JP", direction: -1 },
  { id: 89, content: "我喜欢在最后期限前冲刺", dimension: "JP", direction: 1 },
  { id: 90, content: "我喜欢有明确的目标", dimension: "JP", direction: -1 },
  { id: 91, content: "我喜欢探索过程中的发现", dimension: "JP", direction: 1 },
  { id: 92, content: "我喜欢有条理地工作", dimension: "JP", direction: -1 },
  { id: 93, content: "我喜欢适应性强的工作方式", dimension: "JP", direction: 1 }
];

// 导出题库
export default fullQuestions;
